# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161121_1836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('name', 'surname', 'birth_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('title', 'lc_classification')]),
        ),
    ]
